{
 "title": "PromED",
 "tags": [
  "promstack",
  "provisioned"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "short_interval",
    "query": "1m,10m,15m,30m,1h,2h,3h,4h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": "label_values(discoverer__cache_hits, job)"
   },
   {
    "name": "instance",
    "query": "label_values(discoverer__cache_hits, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Discover Rounds per 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Next Cache Entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__next_cache_entries{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__cache_hits{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AWS API Request per $short_interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$short_interval]))"
    }
   ]
  },
  {
   "title": "Current Cache Entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__current_cache_entries{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "container_instance_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"container_instance_cache\"}",
     "legendFormat": "container_instance_cache"
    }
   ]
  },
  {
   "title": "ec2_instance_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"ec2_instance_cache\"}",
     "legendFormat": "ec2_instance_cache"
    }
   ]
  },
  {
   "title": "AWS API Requests by Method per $short_interval",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (increase(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$short_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Latency by Method over $short_interval",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(discoverer__api_requests_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$short_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "task_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"task_cache\"}",
     "legendFormat": "task_cache"
    }
   ]
  },
  {
   "title": "task_definition_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"task_definition_cache\"}",
     "legendFormat": "task_definition_cache"
    }
   ]
  },
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects collected during GC per 1s over 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "gen {{generation}}"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "virtual mem"
      },
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "resident mem"
      }
     ]
    },
    {
     "title": "Process Memory Deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "deriv(process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "virtual mem"
      },
      {
       "expr": "deriv(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "resident mem"
      }
     ]
    },
    {
     "title": "GC Collections by Gen per 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(python_gc_collections_total{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "gen {{generation}}"
      }
     ]
    },
    {
     "title": "Noncollectable Objects found during GC per 1s by 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_objects_uncollectable_total{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "gen {{generation}}"
      }
     ]
    },
    {
     "title": "Process Started",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"} * 1000"
      }
     ]
    },
    {
     "title": "Process Started",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"} * 1000"
      }
     ]
    }
   ]
  }
 ]
}