{
 "title": "PromED",
 "description": "Prometheus ECS Discoverer",
 "tags": [
  "provisioned",
  "external",
  "promed"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "step", "label": "Min Step", "query": "15s,1m,5m,15m,30m" },
   {
    "name": "job",
    "query": "label_values(discoverer__cache_hits, job)"
   },
   {
    "name": "instance",
    "query": "label_values(discoverer__cache_hits, instance)"
   },
   {
    "name": "method",
    "query": "label_values(discoverer__api_requests_duration_seconds_count, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "Discovery Rounds per 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 60",
     "legendFormat": "Rounds"
    },
    {
     "expr": "sum(rate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1d)) * 60",
     "legendFormat": "Rounds | Offset 1d"
    },
    {
     "expr": "sum(rate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1w)) * 60",
     "legendFormat": "Rounds | Offset 1w"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(min_over_time(up{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "up"
    },
    { "expr": "1", "legendFormat": "red" }
   ]
  },
  {
   "title": "Rounds that took longer than configured interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(discoverer__execution_breaches_total{instance=\"$instance\", job=\"$job\"}[$__range])"
    }
   ]
  },
  {
   "title": "AWS API Requests by Method per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (method) * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Current Cache Entries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__current_cache_entries{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AWS API Requests per 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 60",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1d)) * 60",
     "legendFormat": "Requests | Offset 1d"
    },
    {
     "expr": "sum(\n  rate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1w)\n) * 60",
     "legendFormat": "Requests | Offset 1w"
    }
   ]
  },
  {
   "title": "Request Latency Avg by Method",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(discoverer__api_requests_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\n/\nrate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Discoverer Round Duration Avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(discoverer__round_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\n/\nrate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Duration"
    },
    {
     "expr": "rate(discoverer__round_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1d)\n/\nrate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1d)",
     "legendFormat": "Duration | Offset 1d | LowR"
    },
    {
     "expr": "rate(discoverer__round_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1w)\n/\nrate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1w)",
     "legendFormat": "Duration | Offset 1w | LowR"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_hits{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "container_instance_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"container_instance_cache\"}[$__rate_interval])",
     "legendFormat": "container_instance_cache"
    }
   ]
  },
  {
   "title": "task_definition_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"task_definition_cache\"}[$__rate_interval])",
     "legendFormat": "task_definition_cache"
    }
   ]
  },
  {
   "title": "task_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"task_cache\"}[$__rate_interval])",
     "legendFormat": "task_cache"
    }
   ]
  },
  {
   "title": "ec2_instance_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"ec2_instance_cache\"}[$__rate_interval])",
     "legendFormat": "ec2_instance_cache"
    }
   ]
  },
  { "title": "Python", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Objects collected during GC per 1s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "gen {{generation}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1d)",
     "legendFormat": "Resident Memory | Offset 1d"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval] offset 1w)",
     "legendFormat": "Resident Memory | Offset 1w"
    }
   ]
  },
  {
   "title": "Process Memory Deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "deriv(process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "virtual mem"
    },
    {
     "expr": "deriv(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "resident mem"
    }
   ]
  },
  {
   "title": "GC Collections by Gen per 1s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_collections_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "gen {{generation}}"
    }
   ]
  },
  {
   "title": "Noncollectable Objects found during GC per 1s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "gen {{generation}}"
    }
   ]
  },
  {
   "title": "Process Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Process Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Discover Round Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (le) (increase(discoverer__round_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Marked Targets Successful vs Rejected",
   "type": "graph",
   "description": "This is bad. A target marked as a Prometheus target was rejected. Please check the logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__targets_marked_rejected[$__rate_interval]))",
     "legendFormat": "rejected"
    },
    {
     "expr": "sum(avg_over_time(discoverer__targets[$__rate_interval]))",
     "legendFormat": "successful"
    }
   ]
  },
  {
   "title": "Discoverer Round Duration Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(discoverer__round_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\n/\nrate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "round duration"
    }
   ]
  },
  {
   "title": "Marked Targets",
   "type": "graph",
   "description": "Number of targets marked as Prometheus targets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__targets_marked[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__clusters[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Container Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__container_instances[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__tasks[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Task Infos",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__task_infos[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Task Definitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__task_definitions[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__targets[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Histograms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Latency Histogram",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 84 },
     "repeat": "method",
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 84 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 84 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 93 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } }
 ]
}