{
 "title": "PromED / Alerting",
 "tags": [
  "external",
  "promed",
  "alerting",
  "provisioned"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(up{instance=\"discovery:8080\", job=\"discovery\"}[1m])\n   or on() vector(0)\n)",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{instance=\"discovery:8080\", job=\"discovery\"}[1m])",
     "legendFormat": "resident memory"
    }
   ]
  },
  {
   "title": "Discovery Rounds per 5m < 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(discoverer__round_duration_seconds_count{instance=\"discovery:8080\", job=\"discovery\"}[5m]))",
     "legendFormat": "rounds"
    }
   ]
  },
  {
   "title": "Discovery Round Execution Breaches per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(discoverer__execution_breaches_total{instance=\"discovery:8080\", job=\"discovery\"}[1m]) * 60\n  or on() vector(0)\n)"
    }
   ]
  },
  {
   "title": "( Bucket Latency p100 ) > ( Configured Discovery Interval )",
   "type": "graph",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0,\n  sum by (le) (\n    rate(discoverer__round_duration_seconds_bucket[5m])\n  )\n)\n> bool \navg(discoverer__info_interval_seconds)",
     "legendFormat": "Calc"
    },
    { "expr": "1", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "( Discovery Round Duration ) > ( Configured Discovery Interval )",
   "type": "graph",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "(\n  rate(discoverer__round_duration_seconds_sum[5m])\n  /\n  rate(discoverer__round_duration_seconds_count[5m])\n)\n> bool\n(\n  discoverer__info_interval_seconds\n)",
     "legendFormat": "Calc"
    },
    { "expr": "1", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "( Bucket Latency p100 ) > ( Configured Discovery Interval * 2/3 )",
   "type": "graph",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(1.0,\n    sum by (le) (\n      rate(discoverer__round_duration_seconds_bucket[5m])\n    )\n  )\n  > bool avg(discoverer__info_interval_seconds) * 2/3\n)\nand\n(\n  histogram_quantile(1.0,\n    sum by (le) (\n      rate(discoverer__round_duration_seconds_bucket[5m])\n    )\n  )\n  < bool avg(discoverer__info_interval_seconds)\n)",
     "legendFormat": "Calc"
    },
    { "expr": "1", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "( Discovery Round Duration ) > ( Configured Discovery Interval * 0.5 )",
   "type": "graph",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "(\n  (\n    rate(discoverer__round_duration_seconds_sum[5m])\n    /\n    rate(discoverer__round_duration_seconds_count[5m])\n  )\n  > bool discoverer__info_interval_seconds * 0.5\n)\nand\n(\n  (\n    rate(discoverer__round_duration_seconds_sum[5m])\n    /\n    rate(discoverer__round_duration_seconds_count[5m])\n  )\n  < bool discoverer__info_interval_seconds\n)",
     "legendFormat": "Calc"
    },
    { "expr": "1", "legendFormat": "Limit" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0,\n  sum by (le) (\n    rate(discoverer__round_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "Bucket latency p100"
    },
    {
     "expr": "discoverer__info_interval_seconds",
     "legendFormat": "Configured Discovery Interval"
    },
    {
     "expr": "discoverer__info_interval_seconds * 2/3",
     "legendFormat": "Configured Discovery Interval 2/3"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(discoverer__round_duration_seconds_sum[5m])\n/\nrate(discoverer__round_duration_seconds_count[5m])",
     "legendFormat": "Discovery Round Duration"
    },
    {
     "expr": "discoverer__info_interval_seconds",
     "legendFormat": "Configured Discovery Interval"
    },
    {
     "expr": "discoverer__info_interval_seconds * 0.5",
     "legendFormat": "Configured Discovery Interval 0.5"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "options": {
    "content": "* This dashboard is NOT suitable for interactive discovery. For example if you zoom out far enough you might underfetch and miss data."
   }
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 16, "w": 10, "x": 8, "y": 23 } }
 ]
}