{
 "title": "PromED LowR",
 "description": "Prometheus ECS Discoverer. Low Resolution.",
 "tags": [
  "provisioned",
  "external",
  "promql",
  "promed"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5m,10m,15m,30m,1h,3h,6h,12h,1d" },
   {
    "name": "job",
    "query": "label_values(discoverer__cache_hits, job)"
   },
   {
    "name": "instance",
    "query": "label_values(discoverer__cache_hits, instance)"
   },
   {
    "name": "method",
    "query": "label_values(discoverer__api_requests_duration_seconds_count, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "Discovery Rounds per 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$interval])\n  )\n) * 60",
     "legendFormat": "rounds"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "up"
    },
    { "expr": "1", "legendFormat": "red" }
   ]
  },
  {
   "title": "Rounds that took longer than configured interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(discoverer__execution_breaches_total{instance=\"$instance\", job=\"$job\"}[$__range])"
    }
   ]
  },
  {
   "title": "AWS API Requests by Method per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$interval])\n  ) by (method) > 0\n) * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Current Cache Entries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__current_cache_entries{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AWS API Requests per 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$interval])\n) * 60",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Discoverer Round Duration Avg",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(discoverer__round_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])\n/\nrate(discoverer__round_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "round duration"
    }
   ]
  },
  {
   "title": "Request Latency Avg by Method",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(discoverer__api_requests_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])\n/\nrate(discoverer__api_requests_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_hits{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "container_instance_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"container_instance_cache\"}[$interval])",
     "legendFormat": "container_instance_cache"
    }
   ]
  },
  {
   "title": "task_definition_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"task_definition_cache\"}[$interval])",
     "legendFormat": "task_definition_cache"
    }
   ]
  },
  {
   "title": "task_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"task_cache\"}[$interval])",
     "legendFormat": "task_cache"
    }
   ]
  },
  {
   "title": "ec2_instance_cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(discoverer__cache_misses{job=\"$job\", instance=\"$instance\", name=\"ec2_instance_cache\"}[$interval])",
     "legendFormat": "ec2_instance_cache"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Clusters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__clusters[$interval]))"
    }
   ]
  },
  {
   "title": "Container Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__container_instances[$interval]))"
    }
   ]
  },
  {
   "title": "Task Definitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__task_definitions[$interval]))"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__tasks[$interval]))"
    }
   ]
  },
  {
   "title": "Task Infos",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__task_infos[$interval]))"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(discoverer__targets[$interval]))"
    }
   ]
  },
  {
   "title": "Histograms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Latency Histogram",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
     "repeat": "method",
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 53 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 53 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 62 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$method",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "sum by (le) (increase(discoverer__api_requests_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", method=~\"$method\"}[$interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects collected during GC per 1s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "gen {{generation}}"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "virtual mem"
      },
      {
       "expr": "avg_over_time(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "resident mem"
      }
     ]
    },
    {
     "title": "Process Memory Deriv",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "deriv(process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "virtual mem"
      },
      {
       "expr": "deriv(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "resident mem"
      }
     ]
    },
    {
     "title": "GC Collections by Gen per 1s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_collections_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "gen {{generation}}"
      }
     ]
    },
    {
     "title": "Noncollectable Objects found during GC per 1s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_objects_uncollectable_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "gen {{generation}}"
      }
     ]
    },
    {
     "title": "Process Started",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"} * 1000"
      }
     ]
    },
    {
     "title": "Process Started",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"} * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "options": {
      "content": "* https://github.com/trallnag/prometheus-ecs-discoverer\n* https://grafana.com/grafana/dashboards/12801\n"
     }
    }
   ]
  }
 ]
}